### ISSUE TITLE
Gemini xlsx importer fails on long digits

### ISSUE THREAD

**Issue by bayesianmind** [AUGMXNT/perfi#10]
The `GeminiImporter` uses openpyxl to convert an xlsx into csv. Unfortunately that module seems to have a problem with long numbers.
In a gemini spreadsheet with a long number like -0.0000030335 becomes "Fee (USD) Fee" = "-3.0335e-06"
The decimal_from_str method then ignores the scientific notation and you end up with results like buying hundreds of eth for fractions of a cent. In excel itself, the true number is fully present, so it doesn't seem to be an issue with the actual Excel file, just how openpyxl handles it.

Options:
- (Best) Figure out how to get openpyxl to handle this so we don't lose precision.
- Write a gemini API client that can export the needed data as CSV given a reporting API key. I already have something pretty close to this.
- Sacrifice the precision and add support for scientific notation to `decimal_from_str()`.

Screenshot:
https://imgur.com/a/OSP2Wja

**Comment by bayesianmind** [comment]
Turns out this is a very old long-standing bug in openpyxl and the fix is to use an alternate library or apply a patch: https://stackoverflow.com/questions/13637888/openpyxl-please-do-not-assume-text-as-a-number-when-importing

**Comment by lhl** [comment]
Thanks for chasing that down, will sit down soon and figure the best way to triage. We already use xlsxwriter since it does a better job on writing our export, could look into pylightxl vs openpyxl for reading I guess? https://www.python-excel.org/

Or it might be easier to add a case to look for scientific notation and just have decimal_from_str handle it. @peloriante

**Comment by bayesianmind** [comment]
I tried pylightxl and it does the exact same behavior unfortunately.
Both seem to be keeping the precision, so likely the solution here is having `decimal_from_str` understand scientific notation.

**Comment by peloriante** [comment]
Thanks for this report, @bayesianmind!  I made a small change (See fd63f28) to just float the str inside `decimal_from_str` before we cast to Decimal. I think this will handle parsing out any scientific notation present in the value.  

Can you get latest and try again?

**Comment by bayesianmind** [comment]
Thanks @peloriante!
It would be best to keep precision, especially given how huge some units can be. I tested your patch on my import and was seeing sizable rounding errors, especially for BTC where 1 unit is so expensive.
I put a comment on fd63f28 suggesting a better implementation that preserves all precision.

**Comment by peloriante** [comment]
Great point @bayesianmind 

Merged your suggestion in b0ff639
